// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kurniajigunawan/mikrotik-portal/internal/bridge"
	"github.com/kurniajigunawan/mikrotik-portal/internal/presenter"
	"github.com/kurniajigunawan/mikrotik-portal/internal/presenter/handler"
	"github.com/kurniajigunawan/mikrotik-portal/internal/usecase/mikrotik"
)

// Injectors from wire.go:

func InitHTTPServer() presenter.HTTPServiceInterface {
	routerOS := bridge.NewRouterOSClient()
	usecaseItf := mikrotik.New(routerOS)
	handlerHandler := handler.NewHandler(usecaseItf)
	httpServiceInterface := presenter.NewHTTPService(handlerHandler)
	return httpServiceInterface
}
