// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/kurniajigunawan/mikrotik-portal/internal/bridge"
	"github.com/kurniajigunawan/mikrotik-portal/internal/presenter"
	"github.com/kurniajigunawan/mikrotik-portal/internal/presenter/handler"
	"github.com/kurniajigunawan/mikrotik-portal/internal/usecase/mikrotik"
	"github.com/kurniajigunawan/mikrotik-portal/internal/usecase/render"
)

// Injectors from wire.go:

func InitHTTPServer(ctx context.Context) presenter.HTTPServiceInterface {
	routerOS := bridge.NewRouterOSClient(ctx)
	usecaseItf := mikrotik.New(routerOS)
	renderUsecaseItf := render.New()
	handlerHandler := handler.NewHandler(usecaseItf, renderUsecaseItf)
	httpServiceInterface := presenter.NewHTTPService(handlerHandler)
	return httpServiceInterface
}
